### ISSUE TITLE
Trouble importing python modules for weechat python plugin

### ISSUE THREAD

**Issue by surfninjas** [weechat/weechat#2237]
### Question

OS: Ubuntu 22.04
weechat 4.5.2
python 3.12.7

Hi weechat community!

I am having an issue with importing python modules for a `weechat` plugin I am trying to write. Here is the test script I am running:
```python
import sys

print(sys.path)

import ollama
```

I have set my `PYTHONPATH` to point to the `site-packages` directory of my anaconda install. When I run this test script using `/python reload` in `weechat`, I get the following error:
```
python: stdout/stderr (?): ModuleNotFoundError: No module named 'pydantic_core._pydantic_core'
```

The print statement in the script shows the path to the `site-packages` directory that I point to in my `.bashrc`. As well, I checked if the module exists and it in fact does (`/path/to/anaconda/lib/python3.12/site-packages/pydantic_core/_pydantic_core.pyi`).

I'm not quite sure what is happening because if I run the script outside of `weechat`, it works. Any ideas?

**Comment by flashcode** [comment]
Can you check the output of `/debug libs` in WeeChat to be sure the right Python version is compiled and used by WeeChat?

**Comment by surfninjas** [comment]
@flashcode Thank you for your response!
Here is that output:
```
Libs:
   core:
   	ncurses: 6.3 (patch 20211021)
        gcrypt: 1.9.4
        gnutls: 3.7.3
        curl: 7.81.0
        zlib: 1.2.11
        zstd: 1.4.8
        cJSON: 1.7.15
        spell: aspell 0.60.8
        perl: 5.34.0
        python: 3.10.12
        ruby: 3.0.2

```
